# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EEG_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EEG_Viewer(object):
    def setupUi(self, EEG_Viewer):
        EEG_Viewer.setObjectName("EEG_Viewer")
        EEG_Viewer.resize(1496, 421)
        self.centralwidget = QtWidgets.QWidget(EEG_Viewer)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 251, 381))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.WindowsSize_LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.WindowsSize_LineEdit.setObjectName("WindowsSize_LineEdit")
        self.gridLayout.addWidget(self.WindowsSize_LineEdit, 3, 1, 1, 1)
        self.ButterOrder_LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ButterOrder_LineEdit.setObjectName("ButterOrder_LineEdit")
        self.gridLayout.addWidget(self.ButterOrder_LineEdit, 2, 1, 1, 1)
        self.Import_btn = QtWidgets.QPushButton(self.groupBox)
        self.Import_btn.setObjectName("Import_btn")
        self.gridLayout.addWidget(self.Import_btn, 0, 1, 1, 1)
        self.Channels_ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.Channels_ComboBox.setObjectName("Channels_ComboBox")
        self.gridLayout.addWidget(self.Channels_ComboBox, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.Record_btn = QtWidgets.QPushButton(self.groupBox)
        self.Record_btn.setObjectName("Record_btn")
        self.gridLayout.addWidget(self.Record_btn, 8, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.FiletringMethod_ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.FiletringMethod_ComboBox.setObjectName("FiletringMethod_ComboBox")
        self.FiletringMethod_ComboBox.addItem("")
        self.gridLayout.addWidget(self.FiletringMethod_ComboBox, 5, 1, 1, 1)
        self.FrequencyRange_ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.FrequencyRange_ComboBox.setObjectName("FrequencyRange_ComboBox")
        self.FrequencyRange_ComboBox.addItem("")
        self.FrequencyRange_ComboBox.addItem("")
        self.FrequencyRange_ComboBox.addItem("")
        self.FrequencyRange_ComboBox.addItem("")
        self.FrequencyRange_ComboBox.addItem("")
        self.FrequencyRange_ComboBox.addItem("")
        self.gridLayout.addWidget(self.FrequencyRange_ComboBox, 4, 1, 1, 1)
        self.Spectrogram_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.Spectrogram_radioButton.setObjectName("Spectrogram_radioButton")
        self.gridLayout.addWidget(self.Spectrogram_radioButton, 6, 0, 1, 1)
        self.Filename_btn = QtWidgets.QPushButton(self.groupBox)
        self.Filename_btn.setObjectName("Filename_btn")
        self.gridLayout.addWidget(self.Filename_btn, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.AddMarker_btn = QtWidgets.QPushButton(self.groupBox)
        self.AddMarker_btn.setObjectName("AddMarker_btn")
        self.gridLayout.addWidget(self.AddMarker_btn, 9, 0, 1, 1)
        self.Start_btn = QtWidgets.QPushButton(self.groupBox)
        self.Start_btn.setObjectName("Start_btn")
        self.gridLayout.addWidget(self.Start_btn, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.Markers_ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.Markers_ComboBox.setObjectName("Markers_ComboBox")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.gridLayout.addWidget(self.Markers_ComboBox, 9, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 7, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 10, 751, 381))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.EEG_monitor = Monitor_EEG_plotter(self.groupBox_2)
        self.EEG_monitor.setObjectName("EEG_monitor")
        self.horizontalLayout.addWidget(self.EEG_monitor)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.groupBox_2)
        self.verticalScrollBar.setProperty("value", 0)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout.addWidget(self.verticalScrollBar)
        self.scale_Slider = QtWidgets.QSlider(self.centralwidget)
        self.scale_Slider.setGeometry(QtCore.QRect(1040, 10, 20, 160))
        self.scale_Slider.setProperty("value", 50)
        self.scale_Slider.setOrientation(QtCore.Qt.Vertical)
        self.scale_Slider.setObjectName("scale_Slider")
        self.space_Slider = QtWidgets.QSlider(self.centralwidget)
        self.space_Slider.setGeometry(QtCore.QRect(1040, 210, 20, 160))
        self.space_Slider.setProperty("value", 0)
        self.space_Slider.setOrientation(QtCore.Qt.Vertical)
        self.space_Slider.setObjectName("space_Slider")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1030, 170, 41, 18))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1030, 370, 41, 18))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(1080, 10, 401, 381))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Frequency_monitor = Monitor_Frequency_plotter(self.groupBox_3)
        self.Frequency_monitor.setObjectName("Frequency_monitor")
        self.horizontalLayout_2.addWidget(self.Frequency_monitor)
        EEG_Viewer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EEG_Viewer)
        self.statusbar.setObjectName("statusbar")
        EEG_Viewer.setStatusBar(self.statusbar)

        self.retranslateUi(EEG_Viewer)
        QtCore.QMetaObject.connectSlotsByName(EEG_Viewer)

    def retranslateUi(self, EEG_Viewer):
        _translate = QtCore.QCoreApplication.translate
        EEG_Viewer.setWindowTitle(_translate("EEG_Viewer", "MainWindow"))
        self.groupBox.setTitle(_translate("EEG_Viewer", "Settings"))
        self.label.setText(_translate("EEG_Viewer", "Butter Order"))
        self.WindowsSize_LineEdit.setText(_translate("EEG_Viewer", "6"))
        self.ButterOrder_LineEdit.setText(_translate("EEG_Viewer", "5"))
        self.Import_btn.setText(_translate("EEG_Viewer", "Import Script"))
        self.Record_btn.setText(_translate("EEG_Viewer", "Record"))
        self.label_2.setText(_translate("EEG_Viewer", "Windows Size"))
        self.FiletringMethod_ComboBox.setItemText(0, _translate("EEG_Viewer", "Butterworth"))
        self.FrequencyRange_ComboBox.setItemText(0, _translate("EEG_Viewer", "All"))
        self.FrequencyRange_ComboBox.setItemText(1, _translate("EEG_Viewer", "Gamma"))
        self.FrequencyRange_ComboBox.setItemText(2, _translate("EEG_Viewer", "Beta"))
        self.FrequencyRange_ComboBox.setItemText(3, _translate("EEG_Viewer", "Alpha"))
        self.FrequencyRange_ComboBox.setItemText(4, _translate("EEG_Viewer", "Theta"))
        self.FrequencyRange_ComboBox.setItemText(5, _translate("EEG_Viewer", "Delta"))
        self.Spectrogram_radioButton.setText(_translate("EEG_Viewer", "Spect&rogram"))
        self.Filename_btn.setText(_translate("EEG_Viewer", "File Name"))
        self.label_3.setText(_translate("EEG_Viewer", "Frequency Range"))
        self.AddMarker_btn.setText(_translate("EEG_Viewer", "Add Marker"))
        self.Start_btn.setText(_translate("EEG_Viewer", "Start"))
        self.label_4.setText(_translate("EEG_Viewer", "Filtering Method"))
        self.Markers_ComboBox.setItemText(0, _translate("EEG_Viewer", "label_0"))
        self.Markers_ComboBox.setItemText(1, _translate("EEG_Viewer", "label_1"))
        self.Markers_ComboBox.setItemText(2, _translate("EEG_Viewer", "label_2"))
        self.Markers_ComboBox.setItemText(3, _translate("EEG_Viewer", "label_3"))
        self.Markers_ComboBox.setItemText(4, _translate("EEG_Viewer", "label_4"))
        self.Markers_ComboBox.setItemText(5, _translate("EEG_Viewer", "label_5"))
        self.Markers_ComboBox.setItemText(6, _translate("EEG_Viewer", "label_6"))
        self.Markers_ComboBox.setItemText(7, _translate("EEG_Viewer", "label_7"))
        self.Markers_ComboBox.setItemText(8, _translate("EEG_Viewer", "label_8"))
        self.Markers_ComboBox.setItemText(9, _translate("EEG_Viewer", "label_9"))
        self.groupBox_2.setTitle(_translate("EEG_Viewer", "EEG Monitor"))
        self.label_5.setText(_translate("EEG_Viewer", "Scale"))
        self.label_6.setText(_translate("EEG_Viewer", "Space"))
        self.groupBox_3.setTitle(_translate("EEG_Viewer", "Spectral Monitor"))

from QTDesigner.Monitor_EEG_plotter import Monitor_EEG_plotter
from QTDesigner.Monitor_Frequency_plotter import Monitor_Frequency_plotter
