# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VIDEO_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 880)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.models_listWidget = QtWidgets.QListWidget(self.groupBox)
        self.models_listWidget.setObjectName("models_listWidget")
        self.gridLayout.addWidget(self.models_listWidget, 2, 0, 1, 2)
        self.AddMarker_btn = QtWidgets.QPushButton(self.groupBox)
        self.AddMarker_btn.setObjectName("AddMarker_btn")
        self.gridLayout.addWidget(self.AddMarker_btn, 4, 0, 1, 1)
        self.Filename_btn = QtWidgets.QPushButton(self.groupBox)
        self.Filename_btn.setObjectName("Filename_btn")
        self.gridLayout.addWidget(self.Filename_btn, 0, 0, 1, 1)
        self.Markers_ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.Markers_ComboBox.setObjectName("Markers_ComboBox")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.Markers_ComboBox.addItem("")
        self.gridLayout.addWidget(self.Markers_ComboBox, 4, 1, 1, 1)
        self.Import_btn = QtWidgets.QPushButton(self.groupBox)
        self.Import_btn.setObjectName("Import_btn")
        self.gridLayout.addWidget(self.Import_btn, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 2)
        self.Record_btn = QtWidgets.QPushButton(self.groupBox)
        self.Record_btn.setObjectName("Record_btn")
        self.gridLayout.addWidget(self.Record_btn, 3, 1, 1, 1)
        self.Start_btn = QtWidgets.QPushButton(self.groupBox)
        self.Start_btn.setObjectName("Start_btn")
        self.gridLayout.addWidget(self.Start_btn, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.viewer = Monitor_VIDEO_plotter(self.groupBox_2)
        self.viewer.setObjectName("viewer")
        self.verticalLayout.addWidget(self.viewer)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 175))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_8 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_3.addWidget(self.frame_8, 1, 2, 1, 1)
        self.frame_5 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3.addWidget(self.frame_5, 1, 5, 1, 1)
        self.frame_4 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3.addWidget(self.frame_4, 1, 6, 1, 1)
        self.frame_7 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_3.addWidget(self.frame_7, 1, 3, 1, 1)
        self.frame_6 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3.addWidget(self.frame_6, 1, 4, 1, 1)
        self.frame_3 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3.addWidget(self.frame_3, 1, 7, 1, 1)
        self.frame_1 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_1.setObjectName("frame_1")
        self.gridLayout_3.addWidget(self.frame_1, 1, 9, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_3.addWidget(self.graphicsView_2, 1, 0, 1, 1)
        self.frame_10 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_3.addWidget(self.frame_10, 1, 0, 1, 1)
        self.frame_9 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_3.addWidget(self.frame_9, 1, 1, 1, 1)
        self.frame_2 = Monitor_CARROUSEL_plotter(self.groupBox_3)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3.addWidget(self.frame_2, 1, 8, 1, 1)
        self.carrousel_horizontalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.carrousel_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.carrousel_horizontalSlider.setObjectName("carrousel_horizontalSlider")
        self.gridLayout_3.addWidget(self.carrousel_horizontalSlider, 2, 0, 1, 10)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.AddMarker_btn.setText(_translate("MainWindow", "Add Marker"))
        self.Filename_btn.setText(_translate("MainWindow", "File Name"))
        self.Markers_ComboBox.setItemText(0, _translate("MainWindow", "label_0"))
        self.Markers_ComboBox.setItemText(1, _translate("MainWindow", "label_1"))
        self.Markers_ComboBox.setItemText(2, _translate("MainWindow", "label_2"))
        self.Markers_ComboBox.setItemText(3, _translate("MainWindow", "label_3"))
        self.Markers_ComboBox.setItemText(4, _translate("MainWindow", "label_4"))
        self.Markers_ComboBox.setItemText(5, _translate("MainWindow", "label_5"))
        self.Markers_ComboBox.setItemText(6, _translate("MainWindow", "label_6"))
        self.Markers_ComboBox.setItemText(7, _translate("MainWindow", "label_7"))
        self.Markers_ComboBox.setItemText(8, _translate("MainWindow", "label_8"))
        self.Markers_ComboBox.setItemText(9, _translate("MainWindow", "label_9"))
        self.Import_btn.setText(_translate("MainWindow", "Import Script"))
        self.label_4.setText(_translate("MainWindow", "Models"))
        self.Record_btn.setText(_translate("MainWindow", "Record"))
        self.Start_btn.setText(_translate("MainWindow", "Start"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Webcam Monitor"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Carrousel"))

from QTDesigner.Monitor_CARROUSEL_plotter import Monitor_CARROUSEL_plotter
from QTDesigner.Monitor_VIDEO_plotter import Monitor_VIDEO_plotter
